language: node_js
node_js:
  - "10"
  - "12"
  - "node" # latest
cache: yarn
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
  - make lint
  - make test
  - make test-phantom
email:
  on_failure: change
  on_success: never

