language: node_js
node_js:
  - "6"
  - "8"
  - "node" # latest
cache: yarn
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
  - npm run lint
  - npm run test
email:
  on_failure: change
  on_success: never

