# https://www.appveyor.com/docs/appveyor-yml/

environment:
  matrix:
    - node_version: "8"
    - node_version: "6"
    - node_version: "4"
  IE_BIN: "%PROGRAMFILES%\\Internet Explorer\\iexplore.exe"

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"

test_script:
  - npm run test-ie

build: off
