# https://www.appveyor.com/docs/appveyor-yml/

environment:
  matrix:
    - node_version: "12"
    - node_version: "10"
    - node_version: "8"
  IE_BIN: "%PROGRAMFILES%\\Internet Explorer\\iexplore.exe"

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"

build_script:
  - cmd: yarn install

test_script:
  - cmd: yarn run test-ie
