# https://www.appveyor.com/docs/appveyor-yml/

environment:
  matrix:
    - node_version: "7"
    - node_version: "6"
    - node_version: "4"

cache:
  - node_modules

environment:
  IE_BIN: "%PROGRAMFILES%\\Internet Explorer\\iexplorer.exe"

install:
  - ps: Install-Product node $env:node_version
  - choco install -i yarn
  - refreshenv
  - yarn install

cache:
 - "%LOCALAPPDATA%/Yarn"

test_script:
  - npm run test-ie

build: off
